apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: specific-pod-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "update"]
  resourceNames: ["web-pod", "api-pod"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

