apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
  namespace: default
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backup
        spec:
          containers:
          - name: backup
            image: busybox:1.35
            command: ['sh', '-c', 'echo "Backup completed" && date']
          restartPolicy: OnFailure

