apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector-strategy
  namespace: default
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
      - name: fluentd
        image: busybox:1.35
        command: ['sh', '-c', 'echo "Collecting logs" && sleep 3600']

