apiVersion: batch/v1
kind: Job
metadata:
  name: retry-job
  namespace: default
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: worker
        image: busybox:1.35
        command: ['sh', '-c', 'exit 1']  # Will fail and retry
      restartPolicy: Never

