apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
  namespace: default
spec:
  initContainers:
  - name: wait-for-service
    image: busybox:1.35
    command: ['sh', '-c', 'until nslookup web-service; do echo waiting for service; sleep 2; done']
  - name: download-config
    image: busybox:1.35
    command: ['sh', '-c', 'echo "Downloading configuration" && sleep 5']
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80

