apiVersion: v1
kind: Pod
metadata:
  name: pod-init-shared-volume
  namespace: default
spec:
  initContainers:
  - name: init-data
    image: busybox:1.35
    command: ['sh', '-c', 'echo "Initial data" > /shared/data.txt && echo "Config" > /shared/config.txt']
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'cat /shared/data.txt && cat /shared/config.txt && sleep 3600']
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  volumes:
  - name: shared-volume
    emptyDir: {}
