apiVersion: v1
kind: Pod
metadata:
  name: pod-sidecar
  namespace: default
spec:
  containers:
  - name: app
    image: nginx:1.21
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/app
  - name: log-collector
    image: busybox:1.35
    command: ['sh', '-c', 'tail -f /var/log/app/access.log']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/app
  volumes:
  - name: shared-logs
    emptyDir: {}

