# Solution for Scenario 5: Secret Access Denied
# Pod with secret as environment variables

apiVersion: v1
kind: Pod
metadata:
  name: db-client
  namespace: default
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'env && sleep 3600']
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password

