apiVersion: v1
kind: Pod
metadata:
  name: app-with-storage
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    volumeMounts:
    - name: storage
      mountPath: /var/www/html
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-manual

