apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
  namespace: default
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'cat /etc/secrets/username && cat /etc/secrets/password && sleep 3600']
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret

