apiVersion: v1
kind: Pod
metadata:
  name: pod-projected-volume
  namespace: default
  labels:
    app: web
    env: prod
  annotations:
    version: "1.0"
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'ls -la /projected-volume && sleep 3600']
    volumeMounts:
    - name: projected-volume
      mountPath: /projected-volume
      readOnly: true
  volumes:
  - name: projected-volume
    projected:
      sources:
      - configMap:
          name: app-config
      - secret:
          name: db-secret
      - downwardAPI:
          items:
          - path: "pod-name"
            fieldRef:
              fieldPath: metadata.name
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations

