apiVersion: v1
kind: Pod
metadata:
  name: pod-downward-api
  namespace: default
  labels:
    app: web
    env: production
  annotations:
    version: "1.0"
    build: "123"
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'cat /pod-info/* && sleep 3600']
    volumeMounts:
    - name: pod-info
      mountPath: /pod-info
      readOnly: true
  volumes:
  - name: pod-info
    downwardAPI:
      items:
      - path: "pod-name"
        fieldRef:
          fieldPath: metadata.name
      - path: "namespace"
        fieldRef:
          fieldPath: metadata.namespace
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
      - path: "cpu-limit"
        resourceFieldRef:
          containerName: app
          resource: limits.cpu
      - path: "memory-limit"
        resourceFieldRef:
          containerName: app
          resource: limits.memory

