apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: parameterized-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  iops: "3000"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

