apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
  namespace: default
spec:
  tolerations:
  - key: dedicated
    operator: Equal
    value: special
    effect: NoSchedule
  containers:
  - name: app
    image: nginx:1.21

