apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-envfrom
  namespace: default
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'env && sleep 3600']
    envFrom:
    - secretRef:
        name: db-credentials
    - prefix: DB_
      secretRef:
        name: db-credentials

