# Fixed version: Pod with correct startup probe
apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-failure-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    startupProbe:
      httpGet:
        path: /  # Correct endpoint
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 10
      failureThreshold: 30  # Allow more time for startup
    livenessProbe:
      httpGet:
        path: /
        port: 80

