# Example: Pod with startup probe that will fail
apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-failure-pod
  namespace: default
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    startupProbe:
      httpGet:
        path: /health  # This endpoint doesn't exist
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 5
      failureThreshold: 3  # Will fail after 3 attempts
    livenessProbe:
      httpGet:
        path: /
        port: 80

