# Example: Service with selector that doesn't match any pods
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web
    tier: frontend  # This selector might not match existing pods

