# Fixed version: Service with session affinity
apiVersion: v1
kind: Service
metadata:
  name: sticky-service
  namespace: default
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
  sessionAffinity: ClientIP  # Fixed: Added session affinity
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours

