apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    command: ['sh', '-c', 'env && sleep 3600']
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password

