apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: production
spec:
  limits:
  - max:
      storage: 50Gi
    min:
      storage: 1Gi
    default:
      storage: 10Gi
    type: PersistentVolumeClaim
